version: "3.9"

services:
  counter-service:
    image: levis38/go-counter
    build: .
    ports:
      - "9040-9044:12345"
    deploy:
      replicas: 4
    environment:
      MONGODB_URI: "mongodb+srv://test-user:go-counter@countercluster.qocflvg.mongodb.net/?retryWrites=true&w=majority"
      PORT: "12345"