version: "3.9"
services:
  web:
    build: .
    ports:
      - "12345:12345"
    environment:
      MONGODB_URI: "mongodb+srv://test-user:go-counter@countercluster.qocflvg.mongodb.net/?retryWrites=true&w=majority"